#!/usr/bin/env perl

use strict;
use warnings;
use utf8;

use Data::Dumper;
use Getopt::Long;

use constant THREADS_NUM => 5;
use constant DATASET_SIZE => 1000;

# Get options and the input log file
my %options = ();
my @required_options = qw(db_host db_user db_password db_name);
GetOptions(\%options,
    'threads=i',
    'dataset_size=i',
    'help',
    'db_host=s',
    'db_user=s',
    'db_password=s',
    'db_name=s'
) or die "Error in command line arguments";

# Process options
if ($options{help}) {
    print_usage();
    exit(0);
}
$options{threads} //= THREADS_NUM;
$options{dataset_size} //= DATASET_SIZE;
foreach my $opt_name (@required_options) {
    script_fail("$opt_name required") unless ($options{$opt_name});
}

# Check for input maillog file
script_fail("No log files specified") if (scalar(@ARGV) == 0);

script_success();

sub print_usage {
    print << 'USAGE_INFO';
log_parser - Parse maillog file

USAGE:

    log_parser [OPTION ...] <MAIL LOGFILE>

OPTIONS:

    --threads=<THREADS_NUM>
        A number of worker threads to run, default: 5

    --dataset_size=<DATASET_SIZE>
        The size of data that will be loaded from maillog for processing.
        Default: 1000 records (lines)

    --db_host=<DB_HOST>
        Target database hostname/IP-address

    --db_user=<DB_USER>
        DB connection username

    --db_password=<DB_PASSWORD>
        DB connection password

    --db_name=<DB_NAME>
        Target database name

USAGE_INFO
}

sub script_success {
    print "DONE.\n";
    exit(0);
}

sub script_fail {
    my $error_msg = shift;
    print "===> ERROR: $error_msg\n";
    print_usage();
    exit(1);
}

